import { BuildingDef, TroopDef } from './types';

export const GRID_ROWS = 20;
export const GRID_COLS = 20;
export const CELL_SIZE = 40;

export const BUILDING_DEFS: Record<string, BuildingDef> = {
  town_hall: {
    type: 'town_hall',
    name: 'Town Hall',
    nameAr: 'قاعة البلدة',
    description: 'مركز القرية الرئيسي',
    size: 3,
    hitpoints: 3000,
    cost: 0,
    costType: 'gold',
    buildTime: 0,
    icon: '🏰',
    color: '#c8a84e',
    maxLevel: 10,
    upgradeCostMultiplier: 2.5,
    maxStorage: 1000,
  },
  gold_mine: {
    type: 'gold_mine',
    name: 'Gold Mine',
    nameAr: 'منجم الذهب',
    description: 'ينتج الذهب تلقائياً',
    size: 2,
    hitpoints: 600,
    cost: 150,
    costType: 'gold',
    buildTime: 30,
    icon: '⛏️',
    color: '#f5d442',
    productionRate: 50,
    productionType: 'gold',
    maxLevel: 10,
    upgradeCostMultiplier: 1.8,
    maxStorage: 500,
  },
  elixir_collector: {
    type: 'elixir_collector',
    name: 'Elixir Collector',
    nameAr: 'جامع الإكسير',
    description: 'يجمع الإكسير تلقائياً',
    size: 2,
    hitpoints: 600,
    cost: 150,
    costType: 'elixir',
    buildTime: 30,
    icon: '🧪',
    color: '#d946ef',
    productionRate: 50,
    productionType: 'elixir',
    maxLevel: 10,
    upgradeCostMultiplier: 1.8,
    maxStorage: 500,
  },
  gold_storage: {
    type: 'gold_storage',
    name: 'Gold Storage',
    nameAr: 'مخزن الذهب',
    description: 'يخزن الذهب المنتج',
    size: 2,
    hitpoints: 1000,
    cost: 300,
    costType: 'gold',
    buildTime: 60,
    icon: '🏦',
    color: '#eab308',
    maxLevel: 10,
    upgradeCostMultiplier: 2.0,
    maxStorage: 5000,
  },
  elixir_storage: {
    type: 'elixir_storage',
    name: 'Elixir Storage',
    nameAr: 'مخزن الإكسير',
    description: 'يخزن الإكسير المنتج',
    size: 2,
    hitpoints: 1000,
    cost: 300,
    costType: 'elixir',
    buildTime: 60,
    icon: '🏺',
    color: '#a855f7',
    maxLevel: 10,
    upgradeCostMultiplier: 2.0,
    maxStorage: 5000,
  },
  barracks: {
    type: 'barracks',
    name: 'Barracks',
    nameAr: 'الثكنات',
    description: 'تدرب الجنود للمعركة',
    size: 2,
    hitpoints: 800,
    cost: 200,
    costType: 'gold',
    buildTime: 45,
    icon: '⚔️',
    color: '#ef4444',
    maxLevel: 8,
    upgradeCostMultiplier: 2.0,
    maxStorage: 0,
  },
  army_camp: {
    type: 'army_camp',
    name: 'Army Camp',
    nameAr: 'معسكر الجيش',
    description: 'يستضيف الجنود المدربين',
    size: 2,
    hitpoints: 700,
    cost: 250,
    costType: 'gold',
    buildTime: 30,
    icon: '⛺',
    color: '#22c55e',
    maxLevel: 6,
    upgradeCostMultiplier: 1.8,
    maxStorage: 0,
  },
  cannon: {
    type: 'cannon',
    name: 'Cannon',
    nameAr: 'المدفع',
    description: 'يدافع عن القرية من الهجمات',
    size: 1,
    hitpoints: 500,
    cost: 100,
    costType: 'gold',
    buildTime: 20,
    icon: '💥',
    color: '#78716c',
    attackDamage: 30,
    attackRange: 4,
    maxLevel: 10,
    upgradeCostMultiplier: 1.6,
    maxStorage: 0,
  },
  archer_tower: {
    type: 'archer_tower',
    name: 'Archer Tower',
    nameAr: 'برج الرماة',
    description: 'برج دفاعي يطلق الأسهم',
    size: 1,
    hitpoints: 600,
    cost: 200,
    costType: 'gold',
    buildTime: 30,
    icon: '🏹',
    color: '#a16207',
    attackDamage: 25,
    attackRange: 5,
    maxLevel: 10,
    upgradeCostMultiplier: 1.6,
    maxStorage: 0,
  },
  wizard_tower: {
    type: 'wizard_tower',
    name: 'Wizard Tower',
    nameAr: 'برج السحرة',
    description: 'برج سحري قوي للدفاع',
    size: 1,
    hitpoints: 700,
    cost: 500,
    costType: 'elixir',
    buildTime: 45,
    icon: '🔮',
    color: '#7c3aed',
    attackDamage: 50,
    attackRange: 4,
    maxLevel: 8,
    upgradeCostMultiplier: 1.7,
    maxStorage: 0,
  },
  wall: {
    type: 'wall',
    name: 'Wall',
    nameAr: 'الجدار',
    description: 'يحمي القرية من المهاجمين',
    size: 1,
    hitpoints: 300,
    cost: 50,
    costType: 'gold',
    buildTime: 5,
    icon: '🧱',
    color: '#6b7280',
    maxLevel: 10,
    upgradeCostMultiplier: 1.5,
    maxStorage: 0,
  },
};

export const TROOP_DEFS: Record<string, TroopDef> = {
  barbarian: {
    type: 'barbarian',
    name: 'Barbarian',
    nameAr: 'البربري',
    hitpoints: 100,
    damage: 20,
    speed: 1.5,
    range: 0.5,
    cost: 50,
    costType: 'elixir',
    trainingTime: 10,
    housingSpace: 1,
    icon: '🗡️',
    color: '#b45309',
  },
  archer: {
    type: 'archer',
    name: 'Archer',
    nameAr: 'الرامي',
    hitpoints: 70,
    damage: 25,
    speed: 1.8,
    range: 3,
    cost: 80,
    costType: 'elixir',
    trainingTime: 15,
    housingSpace: 1,
    icon: '🏹',
    color: '#15803d',
  },
  giant: {
    type: 'giant',
    name: 'Giant',
    nameAr: 'العملاق',
    hitpoints: 500,
    damage: 15,
    speed: 0.8,
    range: 0.5,
    cost: 150,
    costType: 'elixir',
    trainingTime: 30,
    housingSpace: 5,
    icon: '👹',
    color: '#7c2d12',
  },
  wizard: {
    type: 'wizard',
    name: 'Wizard',
    nameAr: 'الساحر',
    hitpoints: 120,
    damage: 80,
    speed: 1.2,
    range: 3,
    cost: 300,
    costType: 'elixir',
    trainingTime: 45,
    housingSpace: 4,
    icon: '🧙',
    color: '#6d28d9',
  },
  dragon: {
    type: 'dragon',
    name: 'Dragon',
    nameAr: 'التنين',
    hitpoints: 800,
    damage: 120,
    speed: 1.0,
    range: 2.5,
    cost: 1000,
    costType: 'elixir',
    trainingTime: 120,
    housingSpace: 20,
    icon: '🐉',
    color: '#dc2626',
  },
};

export const INITIAL_GOLD = 1000;
export const INITIAL_ELIXIR = 1000;
export const INITIAL_GEMS = 100;
export const MAX_TROOP_CAPACITY = 50;
export const ATTACK_DURATION = 180; // seconds

export function getBuildingCost(type: string, level: number): number {
  const def = BUILDING_DEFS[type];
  if (!def) return 0;
  return Math.floor(def.cost * Math.pow(def.upgradeCostMultiplier, level - 1));
}

export function getBuildingMaxHP(type: string, level: number): number {
  const def = BUILDING_DEFS[type];
  if (!def) return 0;
  return Math.floor(def.hitpoints * (1 + (level - 1) * 0.2));
}

export function getBuildingMaxStorage(type: string, level: number): number {
  const def = BUILDING_DEFS[type];
  if (!def) return 0;
  return Math.floor(def.maxStorage * (1 + (level - 1) * 0.25));
}

export function getProductionRate(type: string, level: number): number {
  const def = BUILDING_DEFS[type];
  if (!def || !def.productionRate) return 0;
  return def.productionRate * (1 + (level - 1) * 0.3);
}