import { GoogleGenAI } from '@google/genai';

export interface SyllableData {
  sound: string;
  arabicObject: string;
  imagePrompt: string;
  objectDescription: string;
  visualType: string;
}

export interface LevelData {
  targetSentence: string;
  arabicTranslation: string;
  arabicTransliteration: string;
  syllables: SyllableData[];
  questBrief: string;
  absurdScene: string;
  memoryReveal: string;
  levelLayout: {
    grid: number[][];
    monsterPositions: {x: number; y: number}[];
    trapPositions: {x: number; y: number}[];
    pigStartPosition: {x: number; y: number};
    starfruitPositions: {x: number; y: number}[];
  };
}

import { getApiKey } from '../src/utils/apiKeyPool';

export const generateLevelData = async (topic: string): Promise<LevelData> => {
  const ai = new GoogleGenAI({ apiKey: getApiKey() });
  const prompt = `
أنت "محرك لعبة" ذكي جداً (Game Master) للعبة 2D (Gesundheit-style).
يجب عليك أن تبتكر جملة إنجليزية حول الموضوع المطلوب (إن وجد) وتقسيمها لمقاطع وتوليد متاهة 2D للعب.

القواعد للمقاطع والجملة:
1. الهدف: جملة إنجليزية بسيطة.
2. التحليل: قسم الجملة لمقاطع صوتية (تستخدم لاحقاً كفخاخ).
3. التجسيد: اربط كل مقطع بكلمة عربية أو شخصية (أنمي/أفلام).
4. وصف الصورة: imagePrompt لتوليد صورة AI بالإنجليزية.
5. المشهد: مشهد مضحك جداً يربطها.

القواعد للمتاهة (levelLayout):
- grid: مصفوفة 10x12 (10 صفوف، 12 عمود). 1=جدار (طوب بني)، 0=مسار.
- اجعل الحواف الخارجية بـ 1 دائماً.
- اجعل المسارات (0) متصلة لتكوين متاهة بسيطة.
- monsterPositions: مصفوفة إحداثيات للوحوش الحمراء (عددها يجب أن يطابق عدد مقاطع الجملة syllables).
- trapPositions: مصفوفة إحداثيات الفخاخ الزرقاء المرقمة (عددها يجب أن يطابق عدد مقاطع الجملة).
- starfruitPositions: 3 مواقع لنجوم يمكن جمعها.
- pigStartPosition: إحداثيات البطل (الثعلب المتعلم).
- تحذير: كل الإحداثيات (x=العمود، y=الصف) يجب أن تكون على مسار (0) وليس جدار (1). تأكد من أن كل عنصر يقع على قيمة 0 في المصفوفة.

مخرجاتك يجب أن تكون JSON فقط.
`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3.6-flash',
      contents: JSON.stringify({ userTopic: topic, prompt }),
      config: {
        responseMimeType: 'application/json',
        responseSchema: {
          type: 'object',
          properties: {
            targetSentence: { type: 'string' },
            arabicTranslation: { type: 'string' },
            arabicTransliteration: { type: 'string' },
            syllables: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  sound: { type: 'string' },
                  arabicObject: { type: 'string' },
                  imagePrompt: { type: 'string' },
                  objectDescription: { type: 'string' },
                  visualType: { type: 'string' }
                },
                required: ['sound', 'arabicObject', 'imagePrompt', 'objectDescription', 'visualType']
              }
            },
            questBrief: { type: 'string' },
            absurdScene: { type: 'string' },
            memoryReveal: { type: 'string' },
            levelLayout: {
              type: 'object',
              properties: {
                grid: { type: 'array', items: { type: 'array', items: { type: 'number' } } },
                monsterPositions: { type: 'array', items: { type: 'object', properties: { x: { type: 'number' }, y: { type: 'number' } } } },
                trapPositions: { type: 'array', items: { type: 'object', properties: { x: { type: 'number' }, y: { type: 'number' } } } },
                pigStartPosition: { type: 'object', properties: { x: { type: 'number' }, y: { type: 'number' } } },
                starfruitPositions: { type: 'array', items: { type: 'object', properties: { x: { type: 'number' }, y: { type: 'number' } } } }
              },
              required: ['grid', 'monsterPositions', 'trapPositions', 'pigStartPosition', 'starfruitPositions']
            }
          },
          required: ['targetSentence', 'arabicTranslation', 'arabicTransliteration', 'syllables', 'questBrief', 'absurdScene', 'memoryReveal', 'levelLayout']
        }
      }
    });

    const text = response.text;
    if (!text) throw new Error("No response from AI");
    
    // Safely parse JSON even if surrounded by markdown blocks
    const cleanedText = text.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
    const data = JSON.parse(cleanedText) as LevelData;
    
    if (!data.levelLayout || !data.levelLayout.grid || data.levelLayout.grid.length < 5) {
        throw new Error("Invalid grid generated by AI");
    }

    // ensure lists match
    while (data.syllables.length > data.levelLayout.monsterPositions.length) {
      data.levelLayout.monsterPositions.push({x: 1, y: 1}); // fallback
      data.levelLayout.trapPositions.push({x: 2, y: 2}); // fallback
    }
    return data;
  } catch (error) {
    console.error("AI Generation Error:", error);
    throw error;
  }
};

