/**
 * Arabic Phonetic Transliteration Helper for Easy7
 * Converts Latin / Romaji / Pinyin text to Arabic pronunciation phonetics
 */

const COMMON_PHONETICS: Record<string, string> = {
  // Japanese common phrases
  'konnichiwa': 'كونّيتشيوا',
  'arigatou': 'أريغاتو',
  'arigato': 'أريغاتو',
  'arigatō': 'أريغاتو',
  'sayounara': 'سايونارا',
  'sayonara': 'سايونارا',
  'hajimemashite': 'هاجيميماشيتي',
  'watashi': 'واتاشي',
  'namae': 'ناماي',
  'desu': 'ديس',
  'ohayou': 'أوهايو',
  'ohayo': 'أوهايو',
  'konbanwa': 'كونبانوا',
  'oyasumi': 'أوياسومي',
  'sumimasen': 'سوميماسِين',
  'gomen': 'غومين',
  'hai': 'هاي',
  'iie': 'إييي',
  'tomodachi': 'توموداتشي',
  'sensei': 'سينسي',
  'nihon': 'نيهون',
  'nihongo': 'نيهونغو',
  'daisuki': 'دايسكي',
  'sugoi': 'سوغوي',
  'kawaii': 'كاوايي',
  'kore': 'كوري',
  'sore': 'سوري',
  'are': 'أري',
  'doko': 'دوكو',
  'dare': 'داري',
  'nani': 'ناني',
  'nan': 'نان',
  'shitsurei': 'شيتسوراي',
  'kudasai': 'كوداساي',
  'onegaishimasu': 'أونيغايشيماس',
  'ja': 'جا',
  'mata': 'ماتا',
  'ashita': 'أشيتا',
  'genki': 'غينكي',
  'daijoubu': 'دايجوبو',
  'wakarimashita': 'واكاريماشيتا',
  'wakarimasen': 'واكاريماسين',

  // Chinese common phrases
  'ni hao': 'ني هاو',
  'nǐ hǎo': 'ني هاو',
  'nihao': 'ني هاو',
  'xie xie': 'شيي شيي',
  'xièxie': 'شيي شيي',
  'xiexie': 'شيي شيي',
  'zai jian': 'زاي جيان',
  'zàijiàn': 'زاي جيان',
  'zaijian': 'زاي جيان',
  'wo jiao': 'وو جياو',
  'wǒ jiào': 'وو جياو',
  'dui bu qi': 'دوي بوتشي',
  'duìbuqǐ': 'دوي بوتشي',
  'mei guan xi': 'مي غوان شي',
  'méiguānxi': 'مي غوان شي',
  'bu ke qi': 'بو كيتشي',
  'bú kèqì': 'بو كيتشي',
  'wo ai ni': 'وو آي ني',
  'wǒ ài nǐ': 'وو آي ني',
  'ming tian jian': 'مينغ تيان جيان',
  'míngtiān jiàn': 'مينغ تيان جيان',
  'hen hao': 'هين هاو',
  'hěn hǎo': 'هين هاو',
  'qing wen': 'تشينغ وين',
  'qǐng wèn': 'تشينغ وين',
  'laoshi': 'لاوشي',
  'lǎoshī': 'لاوشي',
};

// General syllable mapping for Latin -> Arabic phonetics
const PHONETIC_MAP: [RegExp, string][] = [
  // Compound sounds
  [/tsu/gi, 'تسو'],
  [/chi/gi, 'تشي'],
  [/shi/gi, 'شي'],
  [/zha/gi, 'جا'],
  [/zhe/gi, 'جي'],
  [/zhi/gi, 'جر'],
  [/zhu/gi, 'جو'],
  [/zho/gi, 'جو'],
  [/cha/gi, 'تشا'],
  [/che/gi, 'تشي'],
  [/chu/gi, 'تشو'],
  [/cho/gi, 'تشو'],
  [/sha/gi, 'شا'],
  [/she/gi, 'شي'],
  [/shu/gi, 'شو'],
  [/sho/gi, 'شو'],
  [/kya/gi, 'كيا'],
  [/kyo/gi, 'كيو'],
  [/kyu/gi, 'كيو'],
  [/nya/gi, 'نيا'],
  [/nyo/gi, 'نيو'],
  [/nyu/gi, 'نيو'],
  [/rya/gi, 'ريا'],
  [/ryo/gi, 'ريو'],
  [/ryu/gi, 'ريو'],
  [/gya/gi, 'غيا'],
  [/gyo/gi, 'غيو'],
  [/gyu/gi, 'غيو'],
  [/bya/gi, 'بيا'],
  [/byo/gi, 'بيو'],
  [/byu/gi, 'بيو'],
  [/pya/gi, 'بيا'],
  [/pyo/gi, 'بيو'],
  [/pyu/gi, 'بيو'],
  [/xian/gi, 'شيان'],
  [/xiang/gi, 'شيانغ'],
  [/xiao/gi, 'شياو'],
  [/xiong/gi, 'شيونغ'],
  [/xuan/gi, 'شوان'],
  [/xing/gi, 'شينغ'],
  [/xin/gi, 'شين'],
  [/xie/gi, 'شيي'],
  [/xia/gi, 'شيا'],
  [/xiu/gi, 'شيو'],
  [/xu/gi, 'شو'],
  [/xi/gi, 'شي'],
  [/qia/gi, 'تشيا'],
  [/qie/gi, 'تشيي'],
  [/qian/gi, 'تشيان'],
  [/qiang/gi, 'تشيانغ'],
  [/qiao/gi, 'تشياو'],
  [/qing/gi, 'تشينغ'],
  [/qin/gi, 'تشين'],
  [/qiu/gi, 'تشيو'],
  [/qu/gi, 'تشو'],
  [/qi/gi, 'تشي'],
  [/jue/gi, 'جوي'],
  [/juan/gi, 'جوان'],
  [/jiang/gi, 'جيانغ'],
  [/jiao/gi, 'جياو'],
  [/jian/gi, 'جيان'],
  [/jing/gi, 'جينغ'],
  [/jin/gi, 'جين'],
  [/jie/gi, 'جيي'],
  [/ji/gi, 'جي'],

  // Standard syllables
  [/ka/gi, 'كا'],
  [/ki/gi, 'كي'],
  [/ku/gi, 'كو'],
  [/ke/gi, 'كي'],
  [/ko/gi, 'كو'],
  [/sa/gi, 'سا'],
  [/si/gi, 'سي'],
  [/su/gi, 'سو'],
  [/se/gi, 'سي'],
  [/so/gi, 'سو'],
  [/ta/gi, 'تا'],
  [/ti/gi, 'تي'],
  [/tu/gi, 'تو'],
  [/te/gi, 'تي'],
  [/to/gi, 'تو'],
  [/na/gi, 'نا'],
  [/ni/gi, 'ني'],
  [/nu/gi, 'نو'],
  [/ne/gi, 'ني'],
  [/no/gi, 'نو'],
  [/ha/gi, 'ها'],
  [/hi/gi, 'هي'],
  [/hu/gi, 'هو'],
  [/he/gi, 'هي'],
  [/ho/gi, 'هو'],
  [/ma/gi, 'ما'],
  [/mi/gi, 'مي'],
  [/mu/gi, 'مو'],
  [/me/gi, 'مي'],
  [/mo/gi, 'مو'],
  [/ya/gi, 'يا'],
  [/yu/gi, 'يو'],
  [/yo/gi, 'يو'],
  [/ra/gi, 'را'],
  [/ri/gi, 'ري'],
  [/ru/gi, 'رو'],
  [/re/gi, 'ري'],
  [/ro/gi, 'رو'],
  [/wa/gi, 'وا'],
  [/wo/gi, 'وو'],
  [/ga/gi, 'غا'],
  [/gi/gi, 'غي'],
  [/gu/gi, 'غو'],
  [/ge/gi, 'غي'],
  [/go/gi, 'غو'],
  [/za/gi, 'زا'],
  [/zi/gi, 'زي'],
  [/zu/gi, 'زو'],
  [/ze/gi, 'زي'],
  [/zo/gi, 'زو'],
  [/da/gi, 'دا'],
  [/di/gi, 'دي'],
  [/du/gi, 'دو'],
  [/de/gi, 'دي'],
  [/do/gi, 'دو'],
  [/ba/gi, 'با'],
  [/bi/gi, 'بي'],
  [/bu/gi, 'بو'],
  [/be/gi, 'بي'],
  [/bo/gi, 'بو'],
  [/pa/gi, 'با'],
  [/pi/gi, 'بي'],
  [/pu/gi, 'بو'],
  [/pe/gi, 'بي'],
  [/po/gi, 'بو'],
  [/fa/gi, 'فا'],
  [/fi/gi, 'في'],
  [/fu/gi, 'فو'],
  [/fe/gi, 'في'],
  [/fo/gi, 'فو'],
  [/la/gi, 'لا'],
  [/li/gi, 'لي'],
  [/lu/gi, 'لو'],
  [/le/gi, 'لي'],
  [/lo/gi, 'لو'],

  // Vowels
  [/aa|ā/gi, 'آ'],
  [/ii|ī/gi, 'ي'],
  [/uu|ū/gi, 'و'],
  [/ee|ē/gi, 'ي'],
  [/oo|ō/gi, 'و'],
  [/a/gi, 'ا'],
  [/i/gi, 'ي'],
  [/u/gi, 'و'],
  [/e/gi, 'ي'],
  [/o/gi, 'و'],
  [/n(?![aiueo])/gi, 'ن']
];

export function toArabicPhonetics(text: string): string {
  if (!text) return '';
  
  // Clean punctuation for word lookup
  const clean = text.toLowerCase().replace(/[.,!?;:()]/g, '').trim();
  if (COMMON_PHONETICS[clean]) {
    return COMMON_PHONETICS[clean];
  }

  // Tokenize words
  const words = text.split(/\s+/);
  const arabicWords = words.map(word => {
    const wClean = word.toLowerCase().replace(/[.,!?;:()]/g, '');
    if (COMMON_PHONETICS[wClean]) {
      return COMMON_PHONETICS[wClean];
    }

    let converted = word;
    for (const [pattern, replacement] of PHONETIC_MAP) {
      converted = converted.replace(pattern, replacement);
    }
    // Remove any leftover non-Arabic latin characters gracefully
    converted = converted.replace(/[a-zA-Z]/g, '');
    return converted || word;
  });

  return arabicWords.join(' ');
}
