import { BuildingBlueprint, BuildingType, Quest, UpgradeItem, WaveConfig } from '../types/game';

export const BUILDING_BLUEPRINTS: Record<BuildingType, BuildingBlueprint> = {
  town_hall: {
    type: 'town_hall',
    name: 'Pioneer Sentry Hut',
    category: 'village',
    description: 'The humble single hut and sentry spire of your starting realm. Expand through learning.',
    cost: { wood: 100, stone: 80, coins: 50 },
    constructionTime: 5,
    icon: '🛖',
    maxLevel: 5,
    baseHealth: 1000,
    storageBonus: 100,
    populationBonus: 2,
  },
  house: {
    type: 'house',
    name: 'Villager Cottage',
    category: 'village',
    description: 'Provides cozy living quarters. Increases max kingdom population by 3.',
    cost: { wood: 40, stone: 20 },
    constructionTime: 4,
    icon: '🏡',
    maxLevel: 3,
    baseHealth: 350,
    populationBonus: 3,
  },
  warehouse: {
    type: 'warehouse',
    name: 'Grand Warehouse',
    category: 'village',
    description: 'Secure storage depot. Increases maximum Wood, Stone, and Food capacity by +150.',
    cost: { wood: 60, stone: 40 },
    constructionTime: 5,
    icon: '📦',
    maxLevel: 4,
    baseHealth: 500,
    storageBonus: 150,
  },
  lumber_camp: {
    type: 'lumber_camp',
    name: 'Lumber Mill',
    category: 'production',
    description: 'Headquarters for woodcutting. Produces timber automatically and houses lumberjacks.',
    cost: { wood: 50, stone: 15 },
    constructionTime: 4,
    icon: '🪓',
    maxLevel: 3,
    baseHealth: 400,
    productionRate: { resource: 'wood', amount: 4, intervalSec: 5 },
  },
  mine: {
    type: 'mine',
    name: 'Stone Quarry',
    category: 'production',
    description: 'Excavation site for durable stone and ores. Supplies construction materials continuously.',
    cost: { wood: 60, stone: 50, coins: 20 },
    constructionTime: 6,
    icon: '⛏️',
    maxLevel: 3,
    baseHealth: 450,
    productionRate: { resource: 'stone', amount: 4, intervalSec: 6 },
  },
  farm: {
    type: 'farm',
    name: 'Windmill & Farm',
    category: 'production',
    description: 'Generates wholesome food crops required to sustain and recruit eager villagers.',
    cost: { wood: 45, stone: 25 },
    constructionTime: 4,
    icon: '🌾',
    maxLevel: 3,
    baseHealth: 300,
    productionRate: { resource: 'food', amount: 6, intervalSec: 5 },
  },
  market: {
    type: 'market',
    name: 'Merchant Bazaar',
    category: 'village',
    description: 'Lively trade hub. Allows exchanging surplus raw resources for precious Gold Coins and Gems.',
    cost: { wood: 80, stone: 60, coins: 40 },
    constructionTime: 6,
    icon: '⚖️',
    maxLevel: 3,
    baseHealth: 400,
  },
  archer_tower: {
    type: 'archer_tower',
    name: 'Archer Guard Tower',
    category: 'defense',
    description: 'Elevated wooden tower with expert marksmen. Fires rapid piercing arrows at invading beasts.',
    cost: { wood: 50, stone: 30, coins: 25 },
    constructionTime: 5,
    icon: '🏹',
    maxLevel: 4,
    baseHealth: 450,
    defenseStats: {
      damage: 18,
      range: 160,
      attackSpeed: 1.3,
      projectileType: 'arrow',
    },
  },
  cannon_tower: {
    type: 'cannon_tower',
    name: 'Siege Bomb Tower',
    category: 'defense',
    description: 'Heavy fortified artillery tower. Fires explosive cannonballs that deal area-of-effect damage.',
    cost: { wood: 70, stone: 90, coins: 60 },
    constructionTime: 7,
    icon: '💣',
    maxLevel: 4,
    baseHealth: 600,
    defenseStats: {
      damage: 45,
      range: 180,
      attackSpeed: 0.6,
      projectileType: 'cannonball',
      splashRadius: 65,
    },
  },
  magic_tower: {
    type: 'magic_tower',
    name: 'Frost Arcane Spire',
    category: 'defense',
    description: 'Channels mystical elemental frost. Blasts monsters and slows their movement speed by 40%.',
    cost: { stone: 100, coins: 80, gems: 5 },
    constructionTime: 8,
    icon: '🔮',
    maxLevel: 4,
    baseHealth: 500,
    defenseStats: {
      damage: 30,
      range: 170,
      attackSpeed: 1.0,
      projectileType: 'magic',
      slowEffect: 0.4,
    },
  },
  wall: {
    type: 'wall',
    name: 'Spiked Palisade',
    category: 'defense',
    description: 'Heavy wooden barricades that stall and divert monster waves.',
    cost: { wood: 25, stone: 10 },
    constructionTime: 2,
    icon: '🪵',
    maxLevel: 3,
    baseHealth: 700,
  },
};

export const INITIAL_QUESTS: Quest[] = [
  {
    id: 'quest_gather_wood',
    title: 'Timber for the Realm',
    description: 'Approach nearby oak or pine trees and chop 40 Wood with your trusty axe.',
    targetType: 'gather',
    resourceType: 'wood',
    currentAmount: 0,
    targetAmount: 40,
    isCompleted: false,
    reward: { coins: 30, gems: 2 },
  },
  {
    id: 'quest_build_cottage',
    title: 'Shelter the Citizens',
    description: 'Select an empty plot in the village and construct your first Villager Cottage.',
    targetType: 'build',
    buildingType: 'house',
    currentAmount: 0,
    targetAmount: 1,
    isCompleted: false,
    reward: { wood: 25, food: 30, coins: 40 },
  },
  {
    id: 'quest_recruit_worker',
    title: 'Hands to the Plow',
    description: 'Open the Workers management tab and recruit your first Lumberjack to automate gathering.',
    targetType: 'recruit',
    currentAmount: 0,
    targetAmount: 1,
    isCompleted: false,
    reward: { coins: 50, food: 20 },
  },
  {
    id: 'quest_build_warehouse',
    title: 'Expanding the Stores',
    description: 'Build a Grand Warehouse to increase your kingdom storage capacity.',
    targetType: 'build',
    buildingType: 'warehouse',
    currentAmount: 0,
    targetAmount: 1,
    isCompleted: false,
    reward: { stone: 40, coins: 60 },
  },
  {
    id: 'quest_build_defense',
    title: 'Fortify the Perimeter',
    description: 'Construct an Archer Guard Tower on one of the defensive perimeter bastions.',
    targetType: 'build',
    buildingType: 'archer_tower',
    currentAmount: 0,
    targetAmount: 1,
    isCompleted: false,
    reward: { coins: 80, gems: 5 },
  },
  {
    id: 'quest_survive_wave_1',
    title: 'Repel the Goblin Horde',
    description: 'Trigger the Monster Invasion and successfully defend your village against Wave 1.',
    targetType: 'wave',
    currentAmount: 0,
    targetAmount: 1,
    isCompleted: false,
    reward: { coins: 120, gems: 8, wood: 60, stone: 60 },
  },
  {
    id: 'quest_build_market',
    title: 'Commerce & Wealth',
    description: 'Construct a Merchant Bazaar to begin trading raw goods for gold coins.',
    targetType: 'build',
    buildingType: 'market',
    currentAmount: 0,
    targetAmount: 1,
    isCompleted: false,
    reward: { coins: 150, gems: 10 },
  },
  {
    id: 'quest_explore_chests',
    title: 'Realm Explorer',
    description: 'Explore the outer forest boundaries and open 2 hidden treasure caches.',
    targetType: 'explore',
    currentAmount: 0,
    targetAmount: 2,
    isCompleted: false,
    reward: { coins: 200, gems: 15 },
  },
];

export const WAVE_CONFIGURATIONS: WaveConfig[] = [
  {
    waveNumber: 1,
    enemies: [{ type: 'goblin', count: 5, delaySec: 1.2 }],
    reward: { coins: 50, gems: 3, wood: 30, stone: 20 },
  },
  {
    waveNumber: 2,
    enemies: [
      { type: 'goblin', count: 6, delaySec: 1.0 },
      { type: 'fast_goblin', count: 3, delaySec: 1.5 },
    ],
    reward: { coins: 80, gems: 5, wood: 40, stone: 40 },
  },
  {
    waveNumber: 3,
    enemies: [
      { type: 'goblin', count: 8, delaySec: 0.9 },
      { type: 'orc', count: 3, delaySec: 2.0 },
      { type: 'fast_goblin', count: 4, delaySec: 1.2 },
    ],
    reward: { coins: 120, gems: 8, food: 50, stone: 50 },
  },
  {
    waveNumber: 4,
    enemies: [
      { type: 'fast_goblin', count: 8, delaySec: 0.8 },
      { type: 'orc', count: 6, delaySec: 1.4 },
      { type: 'heavy_orc', count: 2, delaySec: 3.0 },
    ],
    reward: { coins: 180, gems: 12, wood: 80, stone: 80 },
  },
  {
    waveNumber: 5,
    enemies: [
      { type: 'goblin', count: 10, delaySec: 0.7 },
      { type: 'orc', count: 8, delaySec: 1.2 },
      { type: 'heavy_orc', count: 4, delaySec: 2.2 },
      { type: 'boss_gargoyle', count: 1, delaySec: 4.0 },
    ],
    reward: { coins: 300, gems: 25, wood: 120, stone: 120, food: 100 },
  },
];

export const UPGRADE_ITEMS: UpgradeItem[] = [
  {
    id: 'hero_damage',
    category: 'hero',
    name: 'Honed Steel Blade',
    description: 'Increases Hero melee attack damage by +6 per level.',
    level: 1,
    maxLevel: 5,
    baseCost: { coins: 40, stone: 30 },
    costMultiplier: 1.6,
    statBonusText: (lvl) => `+${lvl * 6} Attack Damage`,
  },
  {
    id: 'hero_health',
    category: 'hero',
    name: 'Reinforced Plate Armor',
    description: 'Increases Hero maximum health by +35 per level.',
    level: 1,
    maxLevel: 5,
    baseCost: { coins: 35, wood: 40 },
    costMultiplier: 1.5,
    statBonusText: (lvl) => `+${lvl * 35} Max HP`,
  },
  {
    id: 'hero_speed',
    category: 'hero',
    name: 'Boots of Swiftness',
    description: 'Increases Hero movement speed and dash recovery.',
    level: 1,
    maxLevel: 4,
    baseCost: { coins: 50, gems: 2 },
    costMultiplier: 1.7,
    statBonusText: (lvl) => `+${lvl * 12}% Movement Speed`,
  },
  {
    id: 'worker_speed',
    category: 'economy',
    name: 'Guild Work Ethic',
    description: 'Improves villager movement speed and carrying capacity by +25%.',
    level: 1,
    maxLevel: 4,
    baseCost: { coins: 60, food: 40 },
    costMultiplier: 1.6,
    statBonusText: (lvl) => `+${lvl * 25}% Worker Speed`,
  },
  {
    id: 'tower_damage',
    category: 'defense',
    name: 'Fortified Ballistics',
    description: 'Increases all Defense Tower attack damage by +20%.',
    level: 1,
    maxLevel: 5,
    baseCost: { coins: 75, stone: 60, gems: 3 },
    costMultiplier: 1.8,
    statBonusText: (lvl) => `+${lvl * 20}% Tower Damage`,
  },
  {
    id: 'tower_range',
    category: 'defense',
    name: 'Scout Crow Nests',
    description: 'Expands Defense Tower visual target acquisition range by +15%.',
    level: 1,
    maxLevel: 4,
    baseCost: { coins: 65, wood: 70 },
    costMultiplier: 1.6,
    statBonusText: (lvl) => `+${lvl * 15}% Tower Range`,
  },
];
