export type ReviewRating = 1 | 2 | 3 | 4; // 1: Again, 2: Hard, 3: Good, 4: Easy

export type ItemMemoryState = 'new' | 'learning' | 'reviewing' | 'mastered';
export type MemoryVulnerabilityState = 'stable' | 'due' | 'weak' | 'critical';

export interface KnowledgeLocation {
  plotId: string; // e.g. 'plot_town_hall', 'plot_east_1' (Farm), 'plot_west_1' (Lumber), etc.
  buildingType: string;
  buildingName: string;
  nodeIndex: number; // 0, 1, 2, 3, 4
  nodeLabel: string; // e.g. 'Memory Node 01'
  offsetX: number; // Offset relative to building center
  offsetY: number;
  boundEntityRole?: 'farmer' | 'lumberjack' | 'miner' | 'merchant' | 'warrior' | 'villager';
  districtId?: string;
}

export interface LearningItemRecord {
  id: string;
  knowledgeId: string; // Explicit unique Knowledge ID (e.g. 'DE_A1_000127', 'MATH_001')
  subject: string; // e.g., 'German', 'Physics', 'General Knowledge'
  sourceLevelId?: string; // e.g., 'Level A1'
  sourceUnitId?: string; // e.g., 'Unit 1: Greetings'
  sourceLessonId?: string; // e.g., 'Lesson 2: Common Phrases'
  
  primaryText: string; // Front text (e.g. "Wie geht's?")
  secondaryText: string; // Back text (e.g. "How are you?")
  contextOrNotes?: string; // Grammar / usage notes
  categoryTag?: string; // e.g., 'Phrase', 'Vocabulary', 'Formula', 'Rule'

  // Exact Deterministic Physical World Location
  location: KnowledgeLocation;

  // Spaced Repetition Core State (FSRS / SM-2 hybrid)
  createdAt: number;
  lastReviewedAt: number | null;
  nextDueDate: number; // timestamp
  intervalDays: number; // Scheduled days until next review
  stability: number; // Memory stability (days retrievability stays >= 90%)
  difficulty: number; // 1.0 (easiest) to 10.0 (hardest)
  repsCount: number; // Number of successful consecutive reviews
  lapsesCount: number; // Number of times forgotten (rated 'Again')
  state: ItemMemoryState;
  
  history: Array<{
    reviewedAt: number;
    rating: ReviewRating;
    intervalDays: number;
  }>;
}

export interface KnowledgeNodeInstance {
  id: string; // e.g. 'node_plot_east_1_0'
  knowledgeId: string;
  plotId: string;
  nodeIndex: number;
  label: string;
  x: number; // World position X
  y: number; // World position Y
  memoryState: MemoryVulnerabilityState;
  retrievability: number; // 0.0 to 1.0
  hasShield: boolean;
  shieldStrength: number; // 0.0 to 1.0
  shieldMedicineCharge: number; // Medicine repellent potency
  isRepelling: boolean; // Burst animation trigger
  repelTimer: number;
  vulnerableTimer: number;
  pulsePhase: number;
  warningAlarm: boolean;
  item: LearningItemRecord;
}

export interface LearningItemTemplate {
  id: string;
  primaryText: string;
  secondaryText: string;
  contextOrNotes?: string;
  categoryTag?: string;
}

export interface LessonHierarchyNode {
  id: string;
  title: string;
  description?: string;
  items: LearningItemTemplate[];
}

export interface UnitHierarchyNode {
  id: string;
  title: string;
  description?: string;
  lessons: LessonHierarchyNode[];
}

export interface LevelHierarchyNode {
  id: string;
  title: string;
  description?: string;
  units: UnitHierarchyNode[];
}

export interface SubjectCurriculum {
  id: string;
  subjectName: string;
  iconName: string;
  levels: LevelHierarchyNode[];
}

export interface KingdomLearningState {
  tier: 1 | 2 | 3 | 4 | 5;
  developmentStage: number; // 0: Lone Tower, 1: First Shelter, 2: Homestead/Settlement, 3: Village & Farm, 4: Fortified Town, 5: Royal Citadel
  stageName: string;
  stageDescription: string;
  stageNameAr?: string;
  stageDescriptionAr?: string;
  learningPoints: number; // Genuine accumulated learning points
  learningPointsToNextStage: number;
  vitalityScore: number; // 0.0 to 1.0 (overdue items decrease vitality; reviewing restores to 1.0)
  totalItemsActive: number;
  totalItemsMastered: number;
  dueItemsCount: number;
  overdueItemsCount: number;
  streakDays: number;
  lastActiveDate: string;
  todayReviewsCount: number;
  
  // Knowledge Resources generated by study
  essence: number;
  timber: number;
  stone: number;
  gold: number;
  
  // Hero & Tower Defense stats boosted by retention
  heroStats: {
    level: number;
    power: number;
    fireRate: number;
    range: number;
    spireHealth: number;
    maxSpireHealth: number;
    unlockedRunes: string[]; // e.g., 'Tornado', 'Chain Lightning', 'Crystal Beam'
  };

  // District Expansion System
  currentDistrictIndex?: number; // 0: وادي البدايات, 1: مروج الفرسان الشرقية, 2: مرتفعات الحكمة الشمالية
  districtNameAr?: string;
  districtMasteredCount?: number;
  districtCapacity?: number;
  unlockedDistrictsCount?: number;
}
